### PR TITLE
Mlrrc prepipe

### PR DESCRIPTION
**Pull request by johnkerl**
cc @koernepr re https://github.com/johnkerl/miller/issues/363

### CODE REVIEW

**Comment by johnkerl** [comment]
@koernepr there are no other popens triggered by command-line flags so we have good coverage here.

**Comment by koernepr** [comment]
Based on quick testing of the version in the temporary repos and again this version:
- `mlr` now quits with `Parse error at file "./.mlrrc" line 1: prepipe touch you_were_attacked; cat"`; `touch` no longer is executed
- When `MLRRC` is set, both when the referenced file is readable and when it is nonexisting/unreadable, `.mlrrc` in the working directory is no longer being read
- Both `--prepipe-gunzip` and `--prepipe-zcat` worked as expected when tested with a .gzipped file

It would be helpful to have the CVE ID in the fixing commit, so in case it's not much effort for you, maybe you could amend that commit; releasing the fix is more important though of course, especially since the advisory is already public.

Nitpick: The new "There are shorthands ..." paragraph interrupts the documentation's text flow, e.g in the manpage. This can wait until the next release though ...

**Comment by johnkerl** [comment]
Hmm, I thought I fixed the 'There are shorthands ...' ... I'll double-check it.

And I'll include the CVE in the commit message for that, thanks for the tip!! :)

**Comment by johnkerl** [comment]
Merging

**Pull request merged**
