### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by NikosAlexandris**
Fix typos in entry.go and reference-dsl-variables.md.in

### CODE REVIEW

**Review by johnkerl — APPROVED** [review]
thanks!!

**Comment by johnkerl** [comment]
i typo-ed a merge conflict but will it accept it anyway, then fix it on the main branch -- easier that way

thanks @NikosAlexandris !! :)

**Comment by NikosAlexandris** [comment]
> i typo-ed a merge conflict but will it accept it anyway, then fix it on the main branch -- easier that way
> 
> thanks @NikosAlexandris !! :)

Sorry for the noise. Is it because of the initial commit (edits in the `.md` file, instead of the `.md.in`?) which I reverted with another commit (instead of reverting the first commit!)?

**Comment by johnkerl** [comment]
@NikosAlexandris not your fault at all! :)

Just a straightforward merge-conflict resolution -- my mistake, I left out a curly brace while resolving. :)

**Pull request merged**
