### PR TITLE
Fill-empty verb

### PR DESCRIPTION
**Pull request by johnkerl**
https://github.com/johnkerl/miller/issues/503

### CODE REVIEW

**Comment by BEFH** [comment]
Sorry I did not see that you responded right away. Your interim code worked. Do you want me to test the new verb?

**Comment by NikosAlexandris** [comment]
Is this now `mlr fill-down`?

**Comment by johnkerl** [comment]
@NikosAlexandris there's a new `mlr fill-empty`.

I should cut a new release though ...

**Comment by amitbha** [comment]
Suggestion: 
document the verb in https://miller.readthedocs.io/en/latest/reference-main-null-data/#rules-for-null-handling

**Pull request merged**
