### PR TITLE
Manpage

### PR DESCRIPTION
**Pull request by eveith**
I've created a manpage using asciidoc for mlr.

I have created a RPM package on build.opensuse.org, but the RPM linter complains that a manpage for mlr(1) is missing. So I used mlr's excellent --help output to create one. Hope you like it!

### CODE REVIEW

**Comment by SikhNerd** [comment]
FWIW I built this on my test box and it looks real good :+1:

**Comment by johnkerl** [comment]
OSX note: `brew install asciidoc`

**Comment by johnkerl** [comment]
```
$ "xmllint" --nonet --noout --valid "/Users/kerl/pub_http_internet/miller/doc/miller.1.xml"
I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
/Users/kerl/pub_http_internet/miller/doc/miller.1.xml:2: warning: failed to load external entity "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
D DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
                                                                               ^
/Users/kerl/pub_http_internet/miller/doc/miller.1.xml:5: validity error : Validation failed: no DTD found !
<refentry lang="en">
```

**Comment by johnkerl** [comment]
https://trac.torproject.org/projects/tor/ticket/6436 fixes it.

This is really really awesome!!! As a next step (I'll file an issue) would be auto-creating most of the content from `mlr --help` and `mlr --help-all-functions`.

**Pull request merged**
