### PR TITLE
Replace timegm

### PR DESCRIPTION
**Pull request by tkob**
This PR adds mlr_timegm function and replace timegm with mlr_timegm. (Issue #20)

### CODE REVIEW

**Comment by johnkerl** [comment]
Nice, thank you!

**Comment by jirutka** [comment]
This is a quite bad improvement – `mlr_timegm` is not thread-safe!

**Comment by johnkerl** [comment]
@jirutka can you tell me how threads are involved in Miller?

**Comment by johnkerl** [comment]
@jirutka good call!

**Comment by johnkerl** [comment]
@jirutka Miller was ported from C to Go as of 2022, and the C code has been removed from the `main` branch of Miller. I'll add a comment on a branch ...

**Pull request merged**
