### PR TITLE
Sliding window averages

### PR DESCRIPTION
**Pull request by johnkerl**
For https://github.com/johnkerl/miller/issues/362

An example page at https://miller.readthedocs.io/en/latest/ will be on a separate PR.

Example:

* Data generator https://github.com/johnkerl/scripts-math/blob/main/stats/cump -- correlated-uniform Markov process
* This PR for smoothing
* https://github.com/johnkerl/pgr for plotting

```
~/git/johnkerl/scripts-math/stats/cump 0.9 1 1000 | sed 's/^  *//' > ccump.dat
mlr --nidx step -f 1 -a slwin_0_19,slwin_19_0 ccump.dat > ccump_smoothed.dat
pgr -n -nc -p -ms 5 ccump_smoothed.dat &
```
Screen Shot 2022-01-23 at 10 59 16 PM

### CODE REVIEW

**Comment by aborruso** [comment]
Hi @johnkerl I have downloaded [this binary](https://github.com/johnkerl/miller/actions/runs/1737998045), but when I run `step -a slwin-7-2` I have `mlr step: stepper "slwin-7-2" not found`.

What's my error?

Thank you

**Comment by johnkerl** [comment]
@aborruso sorry, late change, it's `slwin_7_2`. Likewise `shift-lead` is `shift_lead`.

I may have missed some doc-spots where I was still referring to `slwin-7-2`; checking now ...

**Comment by johnkerl** [comment]
@aborruso https://github.com/johnkerl/miller/commit/3b4963ea3cd150b89a99e888c331a3e5a74030e2 -- sorry about that -- and thanks for letting me know ...

**Comment by aborruso** [comment]
Great, it works!!!

**Pull request merged**
